version: '3'
services:
  db:
    image: mysql:5.7
    networks:
      - net001
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wordpress000kun
      MYSQL_PASSWORD: wkunpas
  wordpress:
    depends_on:
      - db
    image: wordpress
    networks:
      - net001
    volumes: 
      - wp:/var/www/html
    ports:
      - '11008:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: wordpress000kun
      WORDPRESS_DB_PASSWORD: wkunpass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
  php-apache:
    image: php:7.3-apache
    ports:
      - 80:80
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    depends_on:
      - db
networks:
  net001:
volumes:
  db_data:
  wp:
