version: "3"
services:
  mysql000:
    image: mysql:5.7
    networks:
      - net001
    volumes:
      - mysql000vol1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wordpress000kun
      MYSQL_PASSWORD: wkunpass
  wordpress000:
    depends_on:
      - mysql000
    image: wordpress
    networks:
      - net001
    volumes:
      - wordpress000vol1:/var/www/html
    ports:
      - 11008:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql000
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: wordpress000kun
      WORDPRESS_DB_PASSWORD: wkunpass
networks:
  net001:
volumes:
  mysql000vol1:
  wordpress000vol1:
